site_name: Telegram Explorer
repo_url: https://github.com/guibacellar/TEx/
copyright: Copyright &copy; 2023 - Th3 0bservator

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Home: 'index.md'
  - 'Authentication': 'authentication.md'
  - 'Contact': 'contact.md'
  - 'Configuration':
    - 'Basic Configuration': 'configuration/basic.md'
    - 'Complete Configuration File Example': 'configuration/complete_configuration_file_example.md'
  - 'How to Use':
      - 'Basic Usage': 'how_use/how_to_use_basic.md'
      - 'Connecting to Telegram Servers': 'how_use/usage_connection.md'
      - 'Download/Update Groups': 'how_use/usage_load_groups.md'
      - 'List Groups': 'how_use/usage_list_groups.md'
      - 'Listen Messages': 'how_use/usage_message_listener.md'
      - 'Download Messages': 'how_use/usage_download_messages.md'
  - 'Notification System':
      - 'Discord Notification Hook': 'notification_discord.md'
  - 'Message Finder System':
      - 'RegEx Finder': 'finder_regex.md'
  - 'Reports':
      - 'Export Files': 'report/report_export_files.md'
      - 'HTML Report': 'report/report_html.md'
      - 'Status Report': 'report/report_status.md'
      - 'Text Report': 'report/report_text.md'
  - 'Maintenance':
      - 'Purging Old Data': 'maintenance/purge_old_data.md'

site_author: Th3 0bservator

extra:
  generator: false