site_name: Telegram Explorer
repo_url: https://github.com/guibacellar/TEx/
copyright: Copyright &copy; 2023 - Th3 0bservator

theme:
  name: material
  highlightjs: true
  features:
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes


nav:
  - Home: 'index.md'
  - 'Authentication': 'authentication.md'
  - 'Contact': 'contact.md'
  - 'Configuration':
    - 'Basic Configuration': 'configuration/basic.md'
    - 'Proxy': 'configuration/proxy.md'
    - 'Complete Configuration File Example': 'configuration/complete_configuration_file_example.md'
  - 'How to Use':
      - 'Basic Usage': 'how_use/how_to_use_basic.md'
      - 'Connecting to Telegram Servers': 'how_use/usage_connection.md'
      - 'Download/Update Groups': 'how_use/usage_load_groups.md'
      - 'List Groups': 'how_use/usage_list_groups.md'
      - 'Listen Messages': 'how_use/usage_message_listener.md'
      - 'Download Messages': 'how_use/usage_download_messages.md'
  - 'Notification System':
      - 'Discord Notification Hook': 'notification/notification_discord.md'
      - 'Elastic Search Connector':
          - 'Configuration': 'notification/notification_elasticsearch.md'
          - 'Index Template': 'notification/notification_elasticsearch_index_template.md'
  - 'Message Finder System':
      - 'Catch All': 'finder/finder_catchall.md'
      - 'RegEx Finder': 'finder/finder_regex.md'
  - 'Reports':
      - 'Export Files': 'report/report_export_files.md'
      - 'HTML Report': 'report/report_html.md'
      - 'Status Report': 'report/report_status.md'
      - 'Text Report': 'report/report_text.md'
  - 'Maintenance':
      - 'Purging Old Data': 'maintenance/purge_old_data.md'
  - 'Changelog':
      - 'V0.3.0': 'changelog/v030.md'

site_author: Th3 0bservator

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/th3_0bservator
    - icon: fontawesome/brands/github
      link: https://github.com/guibacellar/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/guilherme-bacellar/